### ISSUE TITLE
this project is dead ?

### ISSUE THREAD

**Issue by ghost** [shravanasati/pyscreenrec#4]
this is cool project don't stop bro

Record Start
^CException in thread Thread-1 (_start_recording):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/archkubi/.local/lib/python3.10/site-packages/pyscreenrec/__init__.py", line 75, in _start_recording
    screenshot(os.path.join(self.screenshot_folder, f"s{i}.jpg"))
  File "/home/archkubi/.local/lib/python3.10/site-packages/pyscreeze/__init__.py", line 506, in _screenshot_linux
    im = Image.open(tmpFilename)
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/archkubi/pyscreenrec_data/s587.jpg'
Record Finish

some times this problem but this is works and so fast bro keep going

import pyscreenrec, time
recorder = pyscreenrec.ScreenRecorder()

recorder.start_recording('rec.mp4', 30)
print("Record Start")

try:
	while True:
		pass
except KeyboardInterrupt:
	recorder.stop_recording() 
	print("Record Finish")

https://user-images.githubusercontent.com/80429360/174443247-63b4a041-a70d-429b-9ac2-f7f6cd1a73a0.mp4

**Comment by shravanasati** [comment]
I want to get back into maintaining this library, thanks for the appreciation.
